### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by JayKarhade** [Shubodh/lidar-image-pretrain-VPR#1]
Hi Shubodh,

Could you also add a requirements.txt file and/or a conda env.yml file ? 

Thanks!

**Comment by Shubodh** [comment]
Hey @JayKarhade ,

Apologies for missing on adding the [`requirements.txt`](https://github.com/Shubodh/lidar-image-pretrain-VPR/blob/master/requirements.txt), it's been added now! [README](https://github.com/Shubodh/lidar-image-pretrain-VPR/tree/master?tab=readme-ov-file#setting-up-the-environment) has been updated accordingly too, please go through it.

Feel free to let me know in case of any further issues! Closing this issue for now.

Thank you for your interest in our work. Please do check [the official website](https://www.shubodhs.ai/liploc) in the future for updates on this work, we plan to release a benchmark soon.
